### ISSUE TITLE
typos, links and other minor bug fixes

### ISSUE THREAD

**Issue by olarubaj** [life-itself/tao#5]
## Job Story

Fixing typos and other minor bugs in the onboarding, working-with-us, and issues/tasks pages.

## Acceptance
* [x] typos corrected
* [x] links corrected
* ~~[ ] code blocks with md not rendering duplicates~~ **moved to #6**

## Tasks
* [x] fix typos on the onboarding, working-with-us, and plans pages
* [x] add links to Further Reading and Getting Help sections on the onboarding page
* [x] update link under Contribute! button -> it points to the old GitLab repo atm
* ~~[ ] investigate why the code blocks with markdown in various places show up duplicated on the page (e.g. the onboarding issue template) and fix it~~ **moved to #6**
